version: '3.0'

volumes:
  timescaledb-storage:
    external: true
  grafana-storage:
    external: true

services:
  db:
    container_name: timescaledb
    image: timescaledev/timescaledb-ha:pg12-latest
    ports:
      - 5432/tcp
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - timescaledb-storage:/home/postgres/pgdata/data

  promscale:
    container_name: promscale
    image: timescale/promscale:latest
    ports:
      - 9201:9201/tcp
    restart: on-failure
    depends_on:
      - db
    environment:
      PROMSCALE_DB_CONNECT_RETRIES: 10
      PROMSCALE_WEB_TELEMETRY_PATH: /metrics-text
      PROMSCALE_DB_URI: postgres://postgres:password@db:5432/postgres?sslmode=disable

  granfana:
    container_name: granfana
    image: grafana/grafana:7.5.8-ubuntu
    user: "472"
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana