

@host = https://api.clockify.me
@workspaceID = 5e86fab7183a8475e0c7a757
@userID = 5e86fab6183a8475e0c7a755

### User
GET  {{host}}/api/v1/user
X-Api-Key: xxx

### Workspace
GET  {{host}}/api/v1/workspaces
X-Api-Key: 
content-type: application/json

### Time entries
@start = 2021-06-13T00:00:00Z
@end = 2021-06-20T00:00:00Z
@hydrated = true
@page = 1
@page-size = 50
GET  {{host}}/api/v1/workspaces/{{workspaceID}}/user/{{userID}}/time-entries?start={{start}}&end={{end}}&hydrated={{hydrated}}&page-size={{page-size}}&&page={{page}}
X-Api-Key: xxx

