{
 "title": "Range Time Series",
 "time": { "from": "2021-06-12T14:00:00.000Z", "to": "2021-06-19T13:59:59.000Z" },
 "panels": [
  {
   "title": "Record Percent",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH label_detail_table AS (\n    SELECT time AT TIME ZONE 'AEST' AS \"time\", value, jsonb(labels) AS label_detail \n    FROM event_log\n    WHERE $__timeFilter(\"time\")\n)\nSELECT \n         sum(COALESCE(value, 0)::numeric) * 60 * 100 /  \n         ($__unixEpochTo() - $__unixEpochFrom())\n\nFROM label_detail_table;"
    }
   ]
  },
  {
   "title": "Output Total/Daily Hrs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH label_detail_table AS (\n    SELECT time AT TIME ZONE 'AEST' AS \"time\", value, jsonb(labels) AS label_detail \n    FROM event_log\n    WHERE $__timeFilter(\"time\")\n),\nsum_table AS (\n\tSELECT\n \t\tround(sum(COALESCE(value, 0))::numeric / 60.0::numeric, 2) AS output_sum_hrs\n \tFROM label_detail_table\nWHERE\n    label_detail_table.label_detail->>'type' = 'self_improving' OR\n    label_detail_table.label_detail->>'type' = 'work'\n)\nSELECT FORMAT('%s/%s', output_sum_hrs, round(output_sum_hrs * 3600 * 24::numeric / ($__unixEpochTo() - $__unixEpochFrom()), 2)\n) \nFROM sum_table;"
    }
   ]
  },
  {
   "title": "Billable Hrs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH label_detail_table AS (\n    SELECT time AT TIME ZONE 'AEST' AS \"time\", value, jsonb(labels) AS label_detail \n    FROM event_log\n    WHERE $__timeFilter(\"time\")\n),\nsum_table AS (\n\tSELECT\n \t\tround(sum(COALESCE(value, 0))::numeric / 60.0::numeric, 2) AS billable_sum_hrs\n \tFROM label_detail_table\nWHERE\n    label_detail_table.label_detail->>'billable' = 'True'\n)\nSELECT FORMAT('%s/%s', billable_sum_hrs, round(billable_sum_hrs * 3600 * 24::numeric / ($__unixEpochTo() - $__unixEpochFrom()), 2)\n) \nFROM sum_table;\n"
    }
   ]
  },
  {
   "title": "Work Hrs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH label_detail_table AS (\n    SELECT time AT TIME ZONE 'AEST' AS \"time\", value, jsonb(labels) AS label_detail \n    FROM event_log\n    WHERE $__timeFilter(\"time\")\n)\nSELECT\n round(sum(COALESCE(value, 0))::numeric / 60.0::numeric, 2) AS work_sum_hrs\nFROM label_detail_table\nWHERE\n    label_detail_table.label_detail->>'type' = 'work';"
    }
   ]
  },
  {
   "title": "Routine Total/Daily Hrs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH label_detail_table AS (\n    SELECT time AT TIME ZONE 'AEST' AS \"time\", value, jsonb(labels) AS label_detail \n    FROM event_log\n    WHERE $__timeFilter(\"time\")\n),\nsum_table AS (\n\tSELECT\n \t\tround(sum(COALESCE(value, 0))::numeric / 60.0::numeric, 2) AS routine_sum_hrs\n \tFROM label_detail_table\nWHERE\n    label_detail_table.label_detail->>'type' = 'routine'\n)\nSELECT FORMAT('%s/%s', routine_sum_hrs, round(routine_sum_hrs * 3600 * 24::numeric / ($__unixEpochTo() - $__unixEpochFrom()), 2)\n) \nFROM sum_table;"
    }
   ]
  },
  {
   "title": "Sports Hrs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH label_detail_table AS (\n    SELECT time AT TIME ZONE 'AEST' AS \"time\", value, jsonb(labels) AS label_detail \n    FROM event_log\n    WHERE $__timeFilter(\"time\")\n),\nsum_table AS (\n\tSELECT\n \t\tround(sum(COALESCE(value, 0))::numeric / 60.0::numeric, 2) AS sports_sum_hrs\n \tFROM label_detail_table\nWHERE\n    label_detail_table.label_detail->>'project' = 'sports'\n)\nSELECT FORMAT('%s/%s', sports_sum_hrs, round(sports_sum_hrs * 3600 * 24::numeric / ($__unixEpochTo() - $__unixEpochFrom()), 2)\n) \nFROM sum_table;"
    }
   ]
  },
  {
   "title": "Bad Hrs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH label_detail_table AS (\n    SELECT time AT TIME ZONE 'AEST' AS \"time\", value, jsonb(labels) AS label_detail \n    FROM event_log\n    WHERE $__timeFilter(\"time\")\n),\nsum_table AS (\n\tSELECT\n \t\tround(sum(COALESCE(value, 0))::numeric / 60.0::numeric, 2) AS bad_sum_hrs\n \tFROM label_detail_table\nWHERE\n    label_detail_table.label_detail->>'type' = 'distracted' OR\n    label_detail_table.label_detail->>'type' = 'dispute' OR\n    label_detail_table.label_detail->>'type' = 'pmo'\n)\nSELECT FORMAT('%s/%s', bad_sum_hrs, round(bad_sum_hrs * 3600 * 24::numeric / ($__unixEpochTo() - $__unixEpochFrom()), 2)\n) \nFROM sum_table;"
    }
   ]
  },
  {
   "title": "The Good",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "WITH label_detail_table AS (\n    SELECT time AT TIME ZONE 'AEST' AS \"time\", value, jsonb(labels) AS label_detail \n    FROM event_log\n    WHERE $__timeFilter(\"time\")\n)\nSELECT\n time_bucket_gapfill('1 day', time, $__timeFrom(), $__timeTo()) AS \"time\",\n COALESCE(sum(value), 0) as billable_sum\nFROM label_detail_table\nWHERE\n    label_detail_table.label_detail->>'billable' = 'True'\nGROUP BY 1\nORDER BY 1;"
    },
    {
     "rawSql": "WITH label_detail_table AS (\n    SELECT time AT TIME ZONE 'AEST' AS \"time\", value, jsonb(labels) AS label_detail \n    FROM event_log\n    WHERE $__timeFilter(\"time\")\n)\nSELECT\n time_bucket_gapfill('1 day', time, $__timeFrom(), $__timeTo()) AS \"time\",\n COALESCE(sum(value), 0) as selfimproving_sum\nFROM label_detail_table\nWHERE\n    label_detail_table.label_detail->>'type' = 'self_improving'\nGROUP BY 1\nORDER BY 1;"
    },
    {
     "rawSql": "WITH label_detail_table AS (\n    SELECT time AT TIME ZONE 'AEST' AS \"time\", value, jsonb(labels) AS label_detail \n    FROM event_log\n    WHERE $__timeFilter(\"time\")\n)\nSELECT\n time_bucket_gapfill('1 day', time, $__timeFrom(), $__timeTo()) AS \"time\",\n COALESCE(sum(value), 0) as work_sum\nFROM label_detail_table\nWHERE\n    label_detail_table.label_detail->>'type' = 'work'\nGROUP BY 1\nORDER BY 1;"
    },
    {
     "rawSql": "WITH label_detail_table AS (\n    SELECT time AT TIME ZONE 'AEST' AS \"time\", value, jsonb(labels) AS label_detail \n    FROM event_log\n    WHERE $__timeFilter(\"time\")\n)\nSELECT\n time_bucket_gapfill('1 day', time, $__timeFrom(), $__timeTo()) AS \"time\",\n COALESCE(sum(value), 0) as output_sum\nFROM label_detail_table\nWHERE\n    label_detail_table.label_detail->>'type' = 'self_improving' OR\n    label_detail_table.label_detail->>'type' = 'work'\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "The Bad",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "WITH label_detail_table AS (\n    SELECT time AT TIME ZONE 'AEST' AS \"time\", value, jsonb(labels) AS label_detail \n    FROM event_log\n    WHERE $__timeFilter(\"time\")\n)\nSELECT\n time_bucket_gapfill('1 day', time, $__timeFrom(), $__timeTo()) AS \"time\",\n COALESCE(sum(value), 0) as distracted_sum\nFROM label_detail_table\nWHERE\n    label_detail_table.label_detail->>'type' = 'distracted'\nGROUP BY 1\nORDER BY 1;"
    },
    {
     "rawSql": "WITH label_detail_table AS (\n    SELECT time AT TIME ZONE 'AEST' AS \"time\", value, jsonb(labels) AS label_detail \n    FROM event_log\n    WHERE $__timeFilter(\"time\")\n)\nSELECT\n time_bucket_gapfill('1 day', time, $__timeFrom(), $__timeTo()) AS \"time\",\n COALESCE(sum(value), 0) as pmo_sum\nFROM label_detail_table\nWHERE\n    label_detail_table.label_detail->>'type' = 'pmo'\nGROUP BY 1\nORDER BY 1;"
    },
    {
     "rawSql": "WITH label_detail_table AS (\n    SELECT time AT TIME ZONE 'AEST' AS \"time\", value, jsonb(labels) AS label_detail \n    FROM event_log\n    WHERE $__timeFilter(\"time\")\n)\nSELECT\n time_bucket_gapfill('1 day', time, $__timeFrom(), $__timeTo()) AS \"time\",\n COALESCE(sum(value), 0) as bad_sum\nFROM label_detail_table\nWHERE\n    (label_detail_table.label_detail->>'type' = 'distracted' OR\n    label_detail_table.label_detail->>'type' = 'pmo' OR\n    label_detail_table.label_detail->>'type' = 'dispute')\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Weekly Routine",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "WITH label_detail_table AS (\n    SELECT time AT TIME ZONE 'AEST' AS \"time\", value, jsonb(labels) AS label_detail \n    from event_log\n    WHERE $__timeFilter(\"time\")\n)\nSELECT \n    time_bucket_gapfill('1 day', time, $__timeFrom(), $__timeTo()) AS \"time\", \n    COALESCE(sum(value), 0) as routine_relax_sum\nFROM label_detail_table \nWHERE \n    label_detail_table.label_detail->>'type' = 'routine' OR\n    label_detail_table.label_detail->>'type' = 'relax'\nGROUP BY 1\nORDER BY 1;"
    },
    {
     "rawSql": "WITH label_detail_table AS (\n    SELECT time AT TIME ZONE 'AEST' AS \"time\", value, jsonb(labels) AS label_detail \n    FROM event_log\n    WHERE $__timeFilter(\"time\")\n)\nSELECT \n  time_bucket_gapfill('1 day', time, $__timeFrom(), $__timeTo()) AS \"time\", \n  COALESCE(sum(value), 0) as recreation_sum\nFROM label_detail_table \nWHERE \n    label_detail_table.label_detail->>'type' = 'recreation'\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Projects",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "WITH label_detail_table AS (\n    SELECT time AT TIME ZONE 'AEST' AS \"time\", value, jsonb(labels) AS label_detail from event_log WHERE $__timeFilter(\"time\")\n)\nSELECT\n time_bucket_gapfill('1 day', time, $__timeFrom(), $__timeTo()) AS \"time\",\n COALESCE(sum(value), 0) as work_sum\nFROM label_detail_table\nWHERE\n    label_detail_table.label_detail->>'project' = 'work'\nGROUP BY 1\nORDER BY 1;"
    },
    {
     "rawSql": "WITH label_detail_table AS (\n    SELECT time AT TIME ZONE 'AEST' AS \"time\", value, jsonb(labels) AS label_detail from event_log \n    WHERE $__timeFilter(\"time\")\n)\nSELECT\n time_bucket_gapfill('1 day', time, $__timeFrom(), $__timeTo()) AS \"time\",\n COALESCE(sum(value), 0) as eng_sum\nFROM label_detail_table\nWHERE\n    label_detail_table.label_detail->>'project' = 'engineering'\nGROUP BY 1\nORDER BY 1;"
    },
    {
     "rawSql": "WITH label_detail_table AS (\n    SELECT time AT TIME ZONE 'AEST' AS \"time\", value, jsonb(labels) AS label_detail from event_log WHERE $__timeFilter(\"time\")\n)\nSELECT\n time_bucket_gapfill('1 day', time, $__timeFrom(), $__timeTo()) AS \"time\",\n COALESCE(sum(value), 0) as oj_sum\nFROM label_detail_table\nWHERE\n    label_detail_table.label_detail->>'project' = 'oj'\nGROUP BY 1\nORDER BY 1;"
    },
    {
     "rawSql": "WITH label_detail_table AS (\n    SELECT time AT TIME ZONE 'AEST' AS \"time\", value, jsonb(labels) AS label_detail from event_log WHERE $__timeFilter(\"time\")\n)\nSELECT\n time_bucket_gapfill('1 day', time, $__timeFrom(), $__timeTo()) AS \"time\",\n COALESCE(sum(value), 0) as math_sum\nFROM label_detail_table\nWHERE\n    label_detail_table.label_detail->>'project' = 'math'\nGROUP BY 1\nORDER BY 1;"
    },
    {
     "rawSql": "WITH label_detail_table AS (\n    SELECT time AT TIME ZONE 'AEST' AS \"time\", value, jsonb(labels) AS label_detail from event_log WHERE $__timeFilter(\"time\")\n)\nSELECT\n time_bucket_gapfill('1 day', time, $__timeFrom(), $__timeTo()) AS \"time\",\n COALESCE(sum(value), 0) as gis_sum\nFROM label_detail_table\nWHERE\n    label_detail_table.label_detail->>'project' = 'gis'\nGROUP BY 1\nORDER BY 1;"
    },
    {
     "rawSql": "WITH label_detail_table AS (\n    SELECT time AT TIME ZONE 'AEST' AS \"time\", value, jsonb(labels) AS label_detail from event_log WHERE $__timeFilter(\"time\")\n)\nSELECT\n time_bucket_gapfill('1 day', time, $__timeFrom(), $__timeTo()) AS \"time\",\n COALESCE(sum(value), 0) as reading_sum\nFROM label_detail_table\nWHERE\n    label_detail_table.label_detail->>'project' = 'usefulreading'\nGROUP BY 1\nORDER BY 1;"
    },
    {
     "rawSql": "WITH label_detail_table AS (\n    SELECT time AT TIME ZONE 'AEST' AS \"time\", value, jsonb(labels) AS label_detail from event_log WHERE $__timeFilter(\"time\")\n)\nSELECT\n time_bucket_gapfill('1 day', time, $__timeFrom(), $__timeTo()) AS \"time\",\n COALESCE(sum(value), 0) as sports_sum\nFROM label_detail_table\nWHERE\n    label_detail_table.label_detail->>'project' = 'sports'\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  }
 ]
}