#!/bin/bash

set -eux

reformat () {
  isort ./lyubishchev/data_model
  black ./lyubishchev/data_model
  # isort ./lyubishchev ./time_report_notebook ./tests # sort imports
  # black ./lyubishchev ./time_report_notebook ./tests # all other code formatting
}

reformat

# is git installed and on the $PATH?
git help &> /dev/null

if [[ -n $(git diff --stat) ]]; then
    echo "Repo state dirty after ./reformat:"
    git diff --stat

    exit 1
fi